version = 0.1

[dev]

[dev.deploy]

[dev.deploy.parameters]
stack_name = "shopify-poc"
s3_prefix = "shopify-poc"
region = "us-east-1"
capabilities = ["CAPABILITY_IAM"]
parameter_overrides = ["Environment=dev"]

[prod]

[prod.deploy]

[prod.deploy.parameters]
stack_name = "shopify-poc"
s3_prefix = "shopify-poc"
region = "us-east-1"
capabilities = ["CAPABILITY_IAM"]
parameter_overrides = ["Environment=prod"]
